In [3]:
import descarteslabs as dl
import numpy as np

In [4]:
aoi = {"coordinates": [[[-9.0915298, 39.3650692], 
                        [-9.0915513, 39.3645093], 
                        [-9.090988, 39.3645342], 
                        [-9.0909773, 39.3649157], 
                        [-9.0909076, 39.3649489], 
                        [-9.0909022, 39.3651148], 
                        [-9.0915298, 39.3650692]]], 
       "type": "Polygon"}

In [5]:
features = dl.metadata.search(
    products='sentinel-3:OLCI_RGB',
    start_time='2017-01-01',
    end_time='2017-03-31',
    limit=80,
    geom=aoi)

print(len(features['features']))
# print(features['features'][30])

60


Iterate through all images and print unique values

In [11]:
for i in features['features']:
    arr, meta = dl.raster.ndarray(
        i['id'],
        bands=['red','green','blue'],
        scales=[[0, 4000],[0, 4000],[0, 4000]],
        data_type='Byte',
        resolution=10,
        cutline=aoi)
   
    print(i['id'])
    print(np.unique(whole_arr, return_counts=True))
    print("_______________")



sentinel-3:OLCI_RGB:meta_2017-01-02-1115_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-03-1049_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-04-1023_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-06-1111_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-07-1045_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-08-1019_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-10-1108_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-11-1042_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
sentinel-3:OLCI_RGB:meta_2017-01-12-1015_29N_07_S3A_v0
(array([0], dtype=uint8), array([126]))
_______________
s

Collect all ids and rasterize all 60 images, print unique values.

In [9]:
ids = [feat['id'] for feat in features['features']]
whole_arr, whole_meta = dl.raster.ndarray(
    ids,
    bands=['red', 'green', 'blue'],
    scales=[[0,4000], [0, 4000], [0, 4000]],
    data_type='Byte',
    resolution=10,
    cutline=aoi
)

print(np.unique(whole_arr, return_counts=True))
     

(array([0], dtype=uint8), array([126]))
